/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	mizarrbacv1alpha1 "k8s.io/api/mizarrbac/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	internal "k8s.io/client-go/applyconfigurations/internal"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	rbacv1 "k8s.io/client-go/applyconfigurations/rbac/v1"
)

// GlobalRoleApplyConfiguration represents an declarative configuration of the GlobalRole type for use
// with apply.
type GlobalRoleApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	RegionSelectors                  []v1.LabelSelectorApplyConfiguration  `json:"regionSelectors,omitempty"`
	ClusterSelectors                 []v1.LabelSelectorApplyConfiguration  `json:"clusterSelectors,omitempty"`
	Rules                            []rbacv1.PolicyRuleApplyConfiguration `json:"rules,omitempty"`
	AggregationRule                  *AggregationRuleApplyConfiguration    `json:"aggregationRule,omitempty"`
}

// GlobalRole constructs an declarative configuration of the GlobalRole type for use with
// apply.
func GlobalRole(name string) *GlobalRoleApplyConfiguration {
	b := &GlobalRoleApplyConfiguration{}
	b.WithName(name)
	b.WithKind("GlobalRole")
	b.WithAPIVersion("rbac.mizargalaxy.mizar-k8s.io/v1alpha1")
	return b
}

// ExtractGlobalRole extracts the applied configuration owned by fieldManager from
// globalRole. If no managedFields are found in globalRole for fieldManager, a
// GlobalRoleApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// globalRole must be a unmodified GlobalRole API object that was retrieved from the Kubernetes API.
// ExtractGlobalRole provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
// Experimental!
func ExtractGlobalRole(globalRole *mizarrbacv1alpha1.GlobalRole, fieldManager string) (*GlobalRoleApplyConfiguration, error) {
	return extractGlobalRole(globalRole, fieldManager, "")
}
func extractGlobalRole(globalRole *mizarrbacv1alpha1.GlobalRole, fieldManager string, subresource string) (*GlobalRoleApplyConfiguration, error) {
	b := &GlobalRoleApplyConfiguration{}
	err := managedfields.ExtractInto(globalRole, internal.Parser().Type("io.k8s.api.mizarrbac.v1alpha1.GlobalRole"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(globalRole.Name)

	b.WithKind("GlobalRole")
	b.WithAPIVersion("rbac.mizargalaxy.mizar-k8s.io/v1alpha1")
	return b, nil
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithKind(value string) *GlobalRoleApplyConfiguration {
	b.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithAPIVersion(value string) *GlobalRoleApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithName(value string) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithGenerateName(value string) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithNamespace(value string) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithUID(value types.UID) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithResourceVersion(value string) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithGeneration(value int64) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithCreationTimestamp(value metav1.Time) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *GlobalRoleApplyConfiguration) WithLabels(entries map[string]string) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *GlobalRoleApplyConfiguration) WithAnnotations(entries map[string]string) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *GlobalRoleApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.OwnerReferences = append(b.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *GlobalRoleApplyConfiguration) WithFinalizers(values ...string) *GlobalRoleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.Finalizers = append(b.Finalizers, values[i])
	}
	return b
}

func (b *GlobalRoleApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithRegionSelectors adds the given value to the RegionSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RegionSelectors field.
func (b *GlobalRoleApplyConfiguration) WithRegionSelectors(values ...*v1.LabelSelectorApplyConfiguration) *GlobalRoleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRegionSelectors")
		}
		b.RegionSelectors = append(b.RegionSelectors, *values[i])
	}
	return b
}

// WithClusterSelectors adds the given value to the ClusterSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ClusterSelectors field.
func (b *GlobalRoleApplyConfiguration) WithClusterSelectors(values ...*v1.LabelSelectorApplyConfiguration) *GlobalRoleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithClusterSelectors")
		}
		b.ClusterSelectors = append(b.ClusterSelectors, *values[i])
	}
	return b
}

// WithRules adds the given value to the Rules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Rules field.
func (b *GlobalRoleApplyConfiguration) WithRules(values ...*rbacv1.PolicyRuleApplyConfiguration) *GlobalRoleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRules")
		}
		b.Rules = append(b.Rules, *values[i])
	}
	return b
}

// WithAggregationRule sets the AggregationRule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AggregationRule field is set to the value of the last call.
func (b *GlobalRoleApplyConfiguration) WithAggregationRule(value *AggregationRuleApplyConfiguration) *GlobalRoleApplyConfiguration {
	b.AggregationRule = value
	return b
}
