
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-kubesphere-io-v1alpha2-eip
  failurePolicy: Fail
  name: validate.eip.network.kubesphere.io
  rules:
  - apiGroups:
    - network.kubesphere.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - eips
  sideEffects: NoneOnDryRun
