{{- if and .Values.speaker.enable .Values.speaker.layer2 (ne .Values.speaker.memberlistSecret "") }}
apiVersion: v1
data:
  key: {{ .Values.speaker.memberlistSecret | b64enc }}
kind: Secret
metadata:
  name: memberlist
{{- end }}
