/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EventRecordApplyConfiguration represents an declarative configuration of the EventRecord type for use
// with apply.
type EventRecordApplyConfiguration struct {
	EventType   *string `json:"eventType,omitempty"`
	CreateTime  *string `json:"createTime,omitempty"`
	LastMessage *string `json:"lastMessage,omitempty"`
}

// EventRecordApplyConfiguration constructs an declarative configuration of the EventRecord type for use with
// apply.
func EventRecord() *EventRecordApplyConfiguration {
	return &EventRecordApplyConfiguration{}
}

// WithEventType sets the EventType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventType field is set to the value of the last call.
func (b *EventRecordApplyConfiguration) WithEventType(value string) *EventRecordApplyConfiguration {
	b.EventType = &value
	return b
}

// WithCreateTime sets the CreateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateTime field is set to the value of the last call.
func (b *EventRecordApplyConfiguration) WithCreateTime(value string) *EventRecordApplyConfiguration {
	b.CreateTime = &value
	return b
}

// WithLastMessage sets the LastMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastMessage field is set to the value of the last call.
func (b *EventRecordApplyConfiguration) WithLastMessage(value string) *EventRecordApplyConfiguration {
	b.LastMessage = &value
	return b
}
