/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// PVCStatusApplyConfiguration represents an declarative configuration of the PVCStatus type for use
// with apply.
type PVCStatusApplyConfiguration struct {
	Name     *string                        `json:"name,omitempty"`
	Status   *v1.PersistentVolumeClaimPhase `json:"status,omitempty"`
	Capacity *v1.ResourceList               `json:"capacity,omitempty"`
}

// PVCStatusApplyConfiguration constructs an declarative configuration of the PVCStatus type for use with
// apply.
func PVCStatus() *PVCStatusApplyConfiguration {
	return &PVCStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PVCStatusApplyConfiguration) WithName(value string) *PVCStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *PVCStatusApplyConfiguration) WithStatus(value v1.PersistentVolumeClaimPhase) *PVCStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *PVCStatusApplyConfiguration) WithCapacity(value v1.ResourceList) *PVCStatusApplyConfiguration {
	b.Capacity = &value
	return b
}
