/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// ResourceLimitApplyConfiguration represents an declarative configuration of the ResourceLimit type for use
// with apply.
type ResourceLimitApplyConfiguration struct {
	Cpu    *resource.Quantity `json:"cpu,omitempty"`
	Memory *resource.Quantity `json:"memory,omitempty"`
}

// ResourceLimitApplyConfiguration constructs an declarative configuration of the ResourceLimit type for use with
// apply.
func ResourceLimit() *ResourceLimitApplyConfiguration {
	return &ResourceLimitApplyConfiguration{}
}

// WithCpu sets the Cpu field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cpu field is set to the value of the last call.
func (b *ResourceLimitApplyConfiguration) WithCpu(value resource.Quantity) *ResourceLimitApplyConfiguration {
	b.Cpu = &value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *ResourceLimitApplyConfiguration) WithMemory(value resource.Quantity) *ResourceLimitApplyConfiguration {
	b.Memory = &value
	return b
}
