/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// StableModelAffinityTermApplyConfiguration represents an declarative configuration of the StableModelAffinityTerm type for use
// with apply.
type StableModelAffinityTermApplyConfiguration struct {
	LabelSelector *v1.LabelSelectorApplyConfiguration `json:"labelSelector,omitempty"`
	Namespaces    []string                            `json:"namespaces,omitempty"`
	TopologyKey   *string                             `json:"topologyKey,omitempty"`
}

// StableModelAffinityTermApplyConfiguration constructs an declarative configuration of the StableModelAffinityTerm type for use with
// apply.
func StableModelAffinityTerm() *StableModelAffinityTermApplyConfiguration {
	return &StableModelAffinityTermApplyConfiguration{}
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *StableModelAffinityTermApplyConfiguration) WithLabelSelector(value *v1.LabelSelectorApplyConfiguration) *StableModelAffinityTermApplyConfiguration {
	b.LabelSelector = value
	return b
}

// WithNamespaces adds the given value to the Namespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Namespaces field.
func (b *StableModelAffinityTermApplyConfiguration) WithNamespaces(values ...string) *StableModelAffinityTermApplyConfiguration {
	for i := range values {
		b.Namespaces = append(b.Namespaces, values[i])
	}
	return b
}

// WithTopologyKey sets the TopologyKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyKey field is set to the value of the last call.
func (b *StableModelAffinityTermApplyConfiguration) WithTopologyKey(value string) *StableModelAffinityTermApplyConfiguration {
	b.TopologyKey = &value
	return b
}
