/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "k8s.io/api/mizarapps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	mizarappsv1alpha1 "k8s.io/client-go/applyconfigurations/mizarapps/v1alpha1"
	testing "k8s.io/client-go/testing"
)

// FakeGlobalQuotas implements GlobalQuotaInterface
type FakeGlobalQuotas struct {
	Fake *FakeMizarappsV1alpha1
	ns   string
}

var globalquotasResource = schema.GroupVersionResource{Group: "apps.mizargalaxy.mizar-k8s.io", Version: "v1alpha1", Resource: "globalquotas"}

var globalquotasKind = schema.GroupVersionKind{Group: "apps.mizargalaxy.mizar-k8s.io", Version: "v1alpha1", Kind: "GlobalQuota"}

// Get takes name of the globalQuota, and returns the corresponding globalQuota object, and an error if there is any.
func (c *FakeGlobalQuotas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlobalQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(globalquotasResource, c.ns, name), &v1alpha1.GlobalQuota{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalQuota), err
}

// List takes label and field selectors, and returns the list of GlobalQuotas that match those selectors.
func (c *FakeGlobalQuotas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlobalQuotaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(globalquotasResource, globalquotasKind, c.ns, opts), &v1alpha1.GlobalQuotaList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GlobalQuotaList{ListMeta: obj.(*v1alpha1.GlobalQuotaList).ListMeta}
	for _, item := range obj.(*v1alpha1.GlobalQuotaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested globalQuotas.
func (c *FakeGlobalQuotas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(globalquotasResource, c.ns, opts))

}

// Create takes the representation of a globalQuota and creates it.  Returns the server's representation of the globalQuota, and an error, if there is any.
func (c *FakeGlobalQuotas) Create(ctx context.Context, globalQuota *v1alpha1.GlobalQuota, opts v1.CreateOptions) (result *v1alpha1.GlobalQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(globalquotasResource, c.ns, globalQuota), &v1alpha1.GlobalQuota{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalQuota), err
}

// Update takes the representation of a globalQuota and updates it. Returns the server's representation of the globalQuota, and an error, if there is any.
func (c *FakeGlobalQuotas) Update(ctx context.Context, globalQuota *v1alpha1.GlobalQuota, opts v1.UpdateOptions) (result *v1alpha1.GlobalQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(globalquotasResource, c.ns, globalQuota), &v1alpha1.GlobalQuota{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalQuota), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGlobalQuotas) UpdateStatus(ctx context.Context, globalQuota *v1alpha1.GlobalQuota, opts v1.UpdateOptions) (*v1alpha1.GlobalQuota, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(globalquotasResource, "status", c.ns, globalQuota), &v1alpha1.GlobalQuota{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalQuota), err
}

// Delete takes name of the globalQuota and deletes it. Returns an error if one occurs.
func (c *FakeGlobalQuotas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(globalquotasResource, c.ns, name, opts), &v1alpha1.GlobalQuota{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGlobalQuotas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(globalquotasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GlobalQuotaList{})
	return err
}

// Patch applies the patch and returns the patched globalQuota.
func (c *FakeGlobalQuotas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(globalquotasResource, c.ns, name, pt, data, subresources...), &v1alpha1.GlobalQuota{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalQuota), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied globalQuota.
func (c *FakeGlobalQuotas) Apply(ctx context.Context, globalQuota *mizarappsv1alpha1.GlobalQuotaApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GlobalQuota, err error) {
	if globalQuota == nil {
		return nil, fmt.Errorf("globalQuota provided to Apply must not be nil")
	}
	data, err := json.Marshal(globalQuota)
	if err != nil {
		return nil, err
	}
	name := globalQuota.Name
	if name == nil {
		return nil, fmt.Errorf("globalQuota.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(globalquotasResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.GlobalQuota{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalQuota), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeGlobalQuotas) ApplyStatus(ctx context.Context, globalQuota *mizarappsv1alpha1.GlobalQuotaApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GlobalQuota, err error) {
	if globalQuota == nil {
		return nil, fmt.Errorf("globalQuota provided to Apply must not be nil")
	}
	data, err := json.Marshal(globalQuota)
	if err != nil {
		return nil, err
	}
	name := globalQuota.Name
	if name == nil {
		return nil, fmt.Errorf("globalQuota.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(globalquotasResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.GlobalQuota{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalQuota), err
}
