/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AuthApplyConfiguration represents an declarative configuration of the Auth type for use
// with apply.
type AuthApplyConfiguration struct {
	Type       *string `json:"type,omitempty"`
	Kubeconfig *string `json:"kubeconfig,omitempty"`
	Token      *string `json:"token,omitempty"`
}

// AuthApplyConfiguration constructs an declarative configuration of the Auth type for use with
// apply.
func Auth() *AuthApplyConfiguration {
	return &AuthApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AuthApplyConfiguration) WithType(value string) *AuthApplyConfiguration {
	b.Type = &value
	return b
}

// WithKubeconfig sets the Kubeconfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubeconfig field is set to the value of the last call.
func (b *AuthApplyConfiguration) WithKubeconfig(value string) *AuthApplyConfiguration {
	b.Kubeconfig = &value
	return b
}

// WithToken sets the Token field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Token field is set to the value of the last call.
func (b *AuthApplyConfiguration) WithToken(value string) *AuthApplyConfiguration {
	b.Token = &value
	return b
}
