/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// KubeletForClusterConfigurationApplyConfiguration represents an declarative configuration of the KubeletForClusterConfiguration type for use
// with apply.
type KubeletForClusterConfigurationApplyConfiguration struct {
	Auth                 *AuthApplyConfiguration   `json:"auth,omitempty"`
	Target               *TargetApplyConfiguration `json:"target,omitempty"`
	Image                *string                   `json:"image,omitempty"`
	Template             *string                   `json:"template,omitempty"`
	ReservedCPU          *resource.Quantity        `json:"reservedCPU,omitempty"`
	ReservedMemory       *resource.Quantity        `json:"reservedMemory,omitempty"`
	TopNodeN             *int32                    `json:"topNodeN,omitempty"`
	HeartbeatFrequency   *int64                    `json:"heartbeatFrequency,omitempty"`
	LeaseDurationSeconds *int64                    `json:"leaseDurationSeconds,omitempty"`
	ForceSyncFrequency   *int64                    `json:"forceSyncFrequency,omitempty"`
	NamespacePrefix      *string                   `json:"namespacePrefix,omitempty"`
}

// KubeletForClusterConfigurationApplyConfiguration constructs an declarative configuration of the KubeletForClusterConfiguration type for use with
// apply.
func KubeletForClusterConfiguration() *KubeletForClusterConfigurationApplyConfiguration {
	return &KubeletForClusterConfigurationApplyConfiguration{}
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithAuth(value *AuthApplyConfiguration) *KubeletForClusterConfigurationApplyConfiguration {
	b.Auth = value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithTarget(value *TargetApplyConfiguration) *KubeletForClusterConfigurationApplyConfiguration {
	b.Target = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithImage(value string) *KubeletForClusterConfigurationApplyConfiguration {
	b.Image = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithTemplate(value string) *KubeletForClusterConfigurationApplyConfiguration {
	b.Template = &value
	return b
}

// WithReservedCPU sets the ReservedCPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReservedCPU field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithReservedCPU(value resource.Quantity) *KubeletForClusterConfigurationApplyConfiguration {
	b.ReservedCPU = &value
	return b
}

// WithReservedMemory sets the ReservedMemory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReservedMemory field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithReservedMemory(value resource.Quantity) *KubeletForClusterConfigurationApplyConfiguration {
	b.ReservedMemory = &value
	return b
}

// WithTopNodeN sets the TopNodeN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopNodeN field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithTopNodeN(value int32) *KubeletForClusterConfigurationApplyConfiguration {
	b.TopNodeN = &value
	return b
}

// WithHeartbeatFrequency sets the HeartbeatFrequency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeartbeatFrequency field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithHeartbeatFrequency(value int64) *KubeletForClusterConfigurationApplyConfiguration {
	b.HeartbeatFrequency = &value
	return b
}

// WithLeaseDurationSeconds sets the LeaseDurationSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaseDurationSeconds field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithLeaseDurationSeconds(value int64) *KubeletForClusterConfigurationApplyConfiguration {
	b.LeaseDurationSeconds = &value
	return b
}

// WithForceSyncFrequency sets the ForceSyncFrequency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForceSyncFrequency field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithForceSyncFrequency(value int64) *KubeletForClusterConfigurationApplyConfiguration {
	b.ForceSyncFrequency = &value
	return b
}

// WithNamespacePrefix sets the NamespacePrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespacePrefix field is set to the value of the last call.
func (b *KubeletForClusterConfigurationApplyConfiguration) WithNamespacePrefix(value string) *KubeletForClusterConfigurationApplyConfiguration {
	b.NamespacePrefix = &value
	return b
}
