/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CRDResourceHookSpecApplyConfiguration represents an declarative configuration of the CRDResourceHookSpec type for use
// with apply.
type CRDResourceHookSpecApplyConfiguration struct {
	Hook         *ResourceCalculateHookApplyConfiguration `json:"hook,omitempty"`
	CRDReference *v1.GroupVersionKindApplyConfiguration   `json:"crdReference,omitempty"`
}

// CRDResourceHookSpecApplyConfiguration constructs an declarative configuration of the CRDResourceHookSpec type for use with
// apply.
func CRDResourceHookSpec() *CRDResourceHookSpecApplyConfiguration {
	return &CRDResourceHookSpecApplyConfiguration{}
}

// WithHook sets the Hook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hook field is set to the value of the last call.
func (b *CRDResourceHookSpecApplyConfiguration) WithHook(value *ResourceCalculateHookApplyConfiguration) *CRDResourceHookSpecApplyConfiguration {
	b.Hook = value
	return b
}

// WithCRDReference sets the CRDReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CRDReference field is set to the value of the last call.
func (b *CRDResourceHookSpecApplyConfiguration) WithCRDReference(value *v1.GroupVersionKindApplyConfiguration) *CRDResourceHookSpecApplyConfiguration {
	b.CRDReference = value
	return b
}
