/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// K8SObjectApplyConfiguration represents an declarative configuration of the K8SObject type for use
// with apply.
type K8SObjectApplyConfiguration struct {
	v1.GroupVersionKindApplyConfiguration `json:",inline"`
	Name                                  *string `json:"name,omitempty"`
}

// K8SObjectApplyConfiguration constructs an declarative configuration of the K8SObject type for use with
// apply.
func K8SObject() *K8SObjectApplyConfiguration {
	return &K8SObjectApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *K8SObjectApplyConfiguration) WithGroup(value string) *K8SObjectApplyConfiguration {
	b.Group = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *K8SObjectApplyConfiguration) WithVersion(value string) *K8SObjectApplyConfiguration {
	b.Version = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *K8SObjectApplyConfiguration) WithKind(value string) *K8SObjectApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *K8SObjectApplyConfiguration) WithName(value string) *K8SObjectApplyConfiguration {
	b.Name = &value
	return b
}
