/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	v1alpha1 "k8s.io/api/mizarapps/v1alpha1"
)

// WorkloadStatusApplyConfiguration represents an declarative configuration of the WorkloadStatus type for use
// with apply.
type WorkloadStatusApplyConfiguration struct {
	Phase              *v1alpha1.WorkloadPhase               `json:"phase,omitempty"`
	ObservedGeneration *int64                                `json:"observedGeneration,omitempty"`
	Conditions         []WorkloadConditionApplyConfiguration `json:"conditions,omitempty"`
	K8SObjectStatus    []K8SObjectStatusApplyConfiguration   `json:"k8sObjectStatus,omitempty"`
	AllocatedResources *v1.ResourceList                      `json:"allocatedResources,omitempty"`
	Region             *string                               `json:"region,omitempty"`
	PhysicalZone       []string                              `json:"physicalZone,omitempty"`
	LogicZone          []string                              `json:"logicZone,omitempty"`
}

// WorkloadStatusApplyConfiguration constructs an declarative configuration of the WorkloadStatus type for use with
// apply.
func WorkloadStatus() *WorkloadStatusApplyConfiguration {
	return &WorkloadStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *WorkloadStatusApplyConfiguration) WithPhase(value v1alpha1.WorkloadPhase) *WorkloadStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *WorkloadStatusApplyConfiguration) WithObservedGeneration(value int64) *WorkloadStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *WorkloadStatusApplyConfiguration) WithConditions(values ...*WorkloadConditionApplyConfiguration) *WorkloadStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithK8SObjectStatus adds the given value to the K8SObjectStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the K8SObjectStatus field.
func (b *WorkloadStatusApplyConfiguration) WithK8SObjectStatus(values ...*K8SObjectStatusApplyConfiguration) *WorkloadStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithK8SObjectStatus")
		}
		b.K8SObjectStatus = append(b.K8SObjectStatus, *values[i])
	}
	return b
}

// WithAllocatedResources sets the AllocatedResources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocatedResources field is set to the value of the last call.
func (b *WorkloadStatusApplyConfiguration) WithAllocatedResources(value v1.ResourceList) *WorkloadStatusApplyConfiguration {
	b.AllocatedResources = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *WorkloadStatusApplyConfiguration) WithRegion(value string) *WorkloadStatusApplyConfiguration {
	b.Region = &value
	return b
}

// WithPhysicalZone adds the given value to the PhysicalZone field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PhysicalZone field.
func (b *WorkloadStatusApplyConfiguration) WithPhysicalZone(values ...string) *WorkloadStatusApplyConfiguration {
	for i := range values {
		b.PhysicalZone = append(b.PhysicalZone, values[i])
	}
	return b
}

// WithLogicZone adds the given value to the LogicZone field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LogicZone field.
func (b *WorkloadStatusApplyConfiguration) WithLogicZone(values ...string) *WorkloadStatusApplyConfiguration {
	for i := range values {
		b.LogicZone = append(b.LogicZone, values[i])
	}
	return b
}
