/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// PreferredSchedulingClusterTermApplyConfiguration represents an declarative configuration of the PreferredSchedulingClusterTerm type for use
// with apply.
type PreferredSchedulingClusterTermApplyConfiguration struct {
	Weight     *int32                                 `json:"weight,omitempty"`
	Preference *ClusterSelectorTermApplyConfiguration `json:"preference,omitempty"`
}

// PreferredSchedulingClusterTermApplyConfiguration constructs an declarative configuration of the PreferredSchedulingClusterTerm type for use with
// apply.
func PreferredSchedulingClusterTerm() *PreferredSchedulingClusterTermApplyConfiguration {
	return &PreferredSchedulingClusterTermApplyConfiguration{}
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *PreferredSchedulingClusterTermApplyConfiguration) WithWeight(value int32) *PreferredSchedulingClusterTermApplyConfiguration {
	b.Weight = &value
	return b
}

// WithPreference sets the Preference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Preference field is set to the value of the last call.
func (b *PreferredSchedulingClusterTermApplyConfiguration) WithPreference(value *ClusterSelectorTermApplyConfiguration) *PreferredSchedulingClusterTermApplyConfiguration {
	b.Preference = value
	return b
}
