/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "k8s.io/api/mizarapps/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CRDResourceHookLister helps list CRDResourceHooks.
// All objects returned here must be treated as read-only.
type CRDResourceHookLister interface {
	// List lists all CRDResourceHooks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.CRDResourceHook, err error)
	// Get retrieves the CRDResourceHook from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.CRDResourceHook, error)
	CRDResourceHookListerExpansion
}

// cRDResourceHookLister implements the CRDResourceHookLister interface.
type cRDResourceHookLister struct {
	indexer cache.Indexer
}

// NewCRDResourceHookLister returns a new CRDResourceHookLister.
func NewCRDResourceHookLister(indexer cache.Indexer) CRDResourceHookLister {
	return &cRDResourceHookLister{indexer: indexer}
}

// List lists all CRDResourceHooks in the indexer.
func (s *cRDResourceHookLister) List(selector labels.Selector) (ret []*v1alpha1.CRDResourceHook, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CRDResourceHook))
	})
	return ret, err
}

// Get retrieves the CRDResourceHook from the index for a given name.
func (s *cRDResourceHookLister) Get(name string) (*v1alpha1.CRDResourceHook, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("crdresourcehook"), name)
	}
	return obj.(*v1alpha1.CRDResourceHook), nil
}
