/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "k8s.io/api/alcor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	alcorv1alpha1 "k8s.io/client-go/applyconfigurations/alcor/v1alpha1"
	testing "k8s.io/client-go/testing"
)

// FakeIPSets implements IPSetInterface
type FakeIPSets struct {
	Fake *FakeAlcorV1alpha1
	ns   string
}

var ipsetsResource = schema.GroupVersionResource{Group: "alcor.io", Version: "v1alpha1", Resource: "ipsets"}

var ipsetsKind = schema.GroupVersionKind{Group: "alcor.io", Version: "v1alpha1", Kind: "IPSet"}

// Get takes name of the iPSet, and returns the corresponding iPSet object, and an error if there is any.
func (c *FakeIPSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IPSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipsetsResource, c.ns, name), &v1alpha1.IPSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPSet), err
}

// List takes label and field selectors, and returns the list of IPSets that match those selectors.
func (c *FakeIPSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IPSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipsetsResource, ipsetsKind, c.ns, opts), &v1alpha1.IPSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IPSetList{ListMeta: obj.(*v1alpha1.IPSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.IPSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iPSets.
func (c *FakeIPSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipsetsResource, c.ns, opts))

}

// Create takes the representation of a iPSet and creates it.  Returns the server's representation of the iPSet, and an error, if there is any.
func (c *FakeIPSets) Create(ctx context.Context, iPSet *v1alpha1.IPSet, opts v1.CreateOptions) (result *v1alpha1.IPSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipsetsResource, c.ns, iPSet), &v1alpha1.IPSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPSet), err
}

// Update takes the representation of a iPSet and updates it. Returns the server's representation of the iPSet, and an error, if there is any.
func (c *FakeIPSets) Update(ctx context.Context, iPSet *v1alpha1.IPSet, opts v1.UpdateOptions) (result *v1alpha1.IPSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipsetsResource, c.ns, iPSet), &v1alpha1.IPSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIPSets) UpdateStatus(ctx context.Context, iPSet *v1alpha1.IPSet, opts v1.UpdateOptions) (*v1alpha1.IPSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ipsetsResource, "status", c.ns, iPSet), &v1alpha1.IPSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPSet), err
}

// Delete takes name of the iPSet and deletes it. Returns an error if one occurs.
func (c *FakeIPSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ipsetsResource, c.ns, name, opts), &v1alpha1.IPSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIPSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IPSetList{})
	return err
}

// Patch applies the patch and returns the patched iPSet.
func (c *FakeIPSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IPSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IPSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPSet), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied iPSet.
func (c *FakeIPSets) Apply(ctx context.Context, iPSet *alcorv1alpha1.IPSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.IPSet, err error) {
	if iPSet == nil {
		return nil, fmt.Errorf("iPSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(iPSet)
	if err != nil {
		return nil, err
	}
	name := iPSet.Name
	if name == nil {
		return nil, fmt.Errorf("iPSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipsetsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.IPSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPSet), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeIPSets) ApplyStatus(ctx context.Context, iPSet *alcorv1alpha1.IPSetApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.IPSet, err error) {
	if iPSet == nil {
		return nil, fmt.Errorf("iPSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(iPSet)
	if err != nil {
		return nil, err
	}
	name := iPSet.Name
	if name == nil {
		return nil, fmt.Errorf("iPSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipsetsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.IPSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPSet), err
}
