/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "k8s.io/api/alcor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	alcorv1alpha1 "k8s.io/client-go/applyconfigurations/alcor/v1alpha1"
	testing "k8s.io/client-go/testing"
)

// FakeStableModels implements StableModelInterface
type FakeStableModels struct {
	Fake *FakeAlcorV1alpha1
	ns   string
}

var stablemodelsResource = schema.GroupVersionResource{Group: "alcor.io", Version: "v1alpha1", Resource: "stablemodels"}

var stablemodelsKind = schema.GroupVersionKind{Group: "alcor.io", Version: "v1alpha1", Kind: "StableModel"}

// Get takes name of the stableModel, and returns the corresponding stableModel object, and an error if there is any.
func (c *FakeStableModels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StableModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(stablemodelsResource, c.ns, name), &v1alpha1.StableModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StableModel), err
}

// List takes label and field selectors, and returns the list of StableModels that match those selectors.
func (c *FakeStableModels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StableModelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(stablemodelsResource, stablemodelsKind, c.ns, opts), &v1alpha1.StableModelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StableModelList{ListMeta: obj.(*v1alpha1.StableModelList).ListMeta}
	for _, item := range obj.(*v1alpha1.StableModelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stableModels.
func (c *FakeStableModels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(stablemodelsResource, c.ns, opts))

}

// Create takes the representation of a stableModel and creates it.  Returns the server's representation of the stableModel, and an error, if there is any.
func (c *FakeStableModels) Create(ctx context.Context, stableModel *v1alpha1.StableModel, opts v1.CreateOptions) (result *v1alpha1.StableModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(stablemodelsResource, c.ns, stableModel), &v1alpha1.StableModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StableModel), err
}

// Update takes the representation of a stableModel and updates it. Returns the server's representation of the stableModel, and an error, if there is any.
func (c *FakeStableModels) Update(ctx context.Context, stableModel *v1alpha1.StableModel, opts v1.UpdateOptions) (result *v1alpha1.StableModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(stablemodelsResource, c.ns, stableModel), &v1alpha1.StableModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StableModel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStableModels) UpdateStatus(ctx context.Context, stableModel *v1alpha1.StableModel, opts v1.UpdateOptions) (*v1alpha1.StableModel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(stablemodelsResource, "status", c.ns, stableModel), &v1alpha1.StableModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StableModel), err
}

// Delete takes name of the stableModel and deletes it. Returns an error if one occurs.
func (c *FakeStableModels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(stablemodelsResource, c.ns, name, opts), &v1alpha1.StableModel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStableModels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(stablemodelsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StableModelList{})
	return err
}

// Patch applies the patch and returns the patched stableModel.
func (c *FakeStableModels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StableModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(stablemodelsResource, c.ns, name, pt, data, subresources...), &v1alpha1.StableModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StableModel), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied stableModel.
func (c *FakeStableModels) Apply(ctx context.Context, stableModel *alcorv1alpha1.StableModelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.StableModel, err error) {
	if stableModel == nil {
		return nil, fmt.Errorf("stableModel provided to Apply must not be nil")
	}
	data, err := json.Marshal(stableModel)
	if err != nil {
		return nil, err
	}
	name := stableModel.Name
	if name == nil {
		return nil, fmt.Errorf("stableModel.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(stablemodelsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.StableModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StableModel), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeStableModels) ApplyStatus(ctx context.Context, stableModel *alcorv1alpha1.StableModelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.StableModel, err error) {
	if stableModel == nil {
		return nil, fmt.Errorf("stableModel provided to Apply must not be nil")
	}
	data, err := json.Marshal(stableModel)
	if err != nil {
		return nil, err
	}
	name := stableModel.Name
	if name == nil {
		return nil, fmt.Errorf("stableModel.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(stablemodelsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.StableModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StableModel), err
}
