apiVersion: apps/v1
kind: Deployment
metadata:
  name: openelb-controller
spec:
  template:
    spec:
      containers:
        # Change the value of image field below to your controller image URL
        - image: kubesphere/openelb-controller:v0.6.0
          name: openelb-controller
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
