apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openelb-speaker
spec:
  template:
    spec:
      containers:
        # Change the value of image field below to your controller image URL
        - image: kubesphere/openelb-speaker:v0.6.0
          name: openelb-speaker
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
