apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openelb-speaker
  labels:
    app: openelb
    component: speaker
spec:
  selector:
    matchLabels:
      app: openelb
      component: speaker
  template:
    metadata:
      labels:
        app: openelb
        component: speaker
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Exists
          effect: NoSchedule
        - key: "node-role.kubernetes.io/control-plane"
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: openelb-admission
      containers:
        - command:
            - openelb-speaker
          args:
            - --api-hosts=:50051
            - --zap-log-level=info
            - --enable-keepalived-vip=false
          image: speaker:latest
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - |
                gobgp -p 50051 global
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: openelb-speaker
          securityContext:
            capabilities:
              add: [ "NET_ADMIN", "SYS_TIME", "NET_RAW", "NET_BIND_SERVICE" ]
          env:
            - name: OPENELB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OPENELB_DSNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      terminationGracePeriodSeconds: 10
      hostNetwork: true

